title: your title
subtitle: your subtitle
author: your name
social:
  twitter: https://twitter.com/yourtwitterid
  github: https://github.com/yourgithubid
  #instagram:
  #weibo:
  #facebook:

per_page: 10        
contact: example@example.com
#avatar: ''
#source: https://github.com/gaotongfei/parchment

theme: genie
